version: '3.9'

services:
  db:
    image: postgres 
    ports:
      - '5432:5432'
    restart: always
    env_file:
      - .env
    environment:
      
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
 